### ISSUE TITLE
Failed to render favourite items after restart

### ISSUE THREAD

**Issue by M1r0zo** [nea89o/Firmament#348]
### Firmament Version

3.11.0+mc1.21.7

### Bug Description

<img width="1919" height="1079" alt="Image" src="https://github.com/user-attachments/assets/fb97613e-19d6-49f2-ba0d-38b73e4e883a" />
Still clickable, just icons and tooltips gone.
Last item always appears to be 'null'
<img width="540" height="108" alt="Image" src="https://github.com/user-attachments/assets/0b0175ec-4e17-4eee-952e-36ac8d4beb41" />

### Minecraft Log

[latest.log](https://github.com/user-attachments/files/23614574/latest.log)

**Comment by Kathund** [comment]
See this tag from the discord
> When your favourites list and inventory buttons are rendering as paintings, the following are likely reasons:
> - You've entered Hypixel/Skyblock too fast
> - You went into a private world first and too fast
> - You have a bugged repository
> 
> To ensure this does not happen, observe the following:
> - Load into Hypixel first before any private worlds.
> - Wait about 15 to 25 seconds before joining Hypixel and an additional 10 or so before opening your inventory.
> - If the above does not work, restart your client and follow the above.

If following the above does not work anyway, please report it here and offer a breakdown of what you are doing and firmament & minecraft version upon launching the game.

**Comment by lineargraph** [comment]
TODO @ self: `delay(10.minutes)` in the repo loader and see which caches gets hit during the render. otherwise mark as CNR and let someone who CR fix it.

**Comment by lineargraph** [comment]
also: there is a chance the fav item list is a separate problem

**Comment by lineargraph** [comment]
ill make the call that 2e6be45b fixes at least the inventory buttons, until someone can confirm otherwise

**Comment by lineargraph** [comment]
likely fixed in e7e67447530bfcf66cf9cf5e25f62a0a5d98efb1

**Comment by AxolotlGmbH** [comment]
The bug is still there. I waited 25 seconds before joining Hypixel, then another 10 seconds till I opened the inventory. The favourite items are still not rendering and at the bottom it said, that REI isnt fully loaded. Iam playing on 1.21.10 and the modversion is 43.0.0. Edit: Sometimes it works, sometimes it doesnt. It seems fairly random.
