### ISSUE TITLE
Storage Overlay Searching

### ISSUE THREAD

**Issue by mossyguy** [nea89o/Firmament#63]
Writing "e" in the search bar, closes the menu.

**Comment by PrinceLikesCookies** [comment]
this is already fixed in the lastest version

**Comment by nea89o** [comment]
On which version does this issue occur?

**Comment by nea89o** [comment]
Latest is generally not a version, but in this specific case this bug is not fixed in any 1.21.3 version. You could change your keybinding to a normal key like tab, or i might eventually do another 1.21.3 release.
